main: net.fycraft.AuthGosch
name: AuthGosch
version: 1.0
description: Plugin responsavel pela autenticacao de todos os jogadores
author: Ricardo Gosch
##
## Commands
commands:
  login:
    description: Comando usado para o jogador autenticar-se
    aliases: [logar, entrar]
##
  register:
    description: Comando usado para o jogador cadastrar-se
    aliases: [registrar, cadastrar]
##
  auth:
    description: Comando principal do sistema de autenticacao